version: '3'

services:
    database:
        build:
            context: ./database
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
        ports:
            - "${DATABASE_EXPOSED_PORT}:3306"
        volumes:
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./database/data:/var/lib/mysql

    php-fpm:
        build:
            context: ./php-fpm
        depends_on:
            - database
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}
        volumes:
            - ../:/var/www
        ports:
            - "${PHP_FPM_EXPOSED_PORT}:9000"

    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites/:/etc/nginx/sites-available
            - ./nginx/conf.d/:/etc/nginx/conf.d
            - ./logs:/var/log
        depends_on:
            - php-fpm
        ports:
            - "${WEBSERVER_EXPOSED_PORT}:80"

    redis:
        build:
            context: ./redis
        restart: always
        ports:
            - "${REDIS_EXPOSED_PORT}:6379"
        volumes:
            - ./redis/data:/root/redis
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_DATABASES=${REDIS_DATABASES}